#!/bin/sh
GAUSS_EXEDIR="$HOME/opt/g09"
G09_EXE_PATH="$GAUSS_EXEDIR/g09" ## points to g16;provide a proper g16 path above
AMBERDIR="undefined"  ## provide your AMBER path
BABELDIR="/usr/local/" ## provide your BABEL path
MATCHDIR="$HOME/Documents/uni/Cambridge/research/codes/MATCH_RELEASE"
GNUPLOT="/usr/local/bin" ## provide your gnuplot path
PYTHON=python2.7
QM_NPROC=4
QM_MEM=2 # GB per core
GAUSSIAN=g09
export GDFONTPATH="undefined" ## fonts path
