#!/bin/sh
source $GAAMPSCRIPTS/routines

cp ../030-generate_structure/mol.xpsf .
cp ../030-generate_structure/mol.inp .
cp ../030-generate_structure/mol.crd .
cp ../030-generate_structure/mol.prm .

Gexe gen-esp mol.inp mol.xpsf $NetCharge  

cp mol-opt.out qm-mol-opt.out
cp cal-esp.out qm-mol-esp.out

Gexe check-b0-theta0 

exit 0
