#!/bin/sh
source $GAAMPSCRIPTS/routines

cp ../030-generate_structure/equiv-org.txt .
cp ../030-generate_structure/mol*.xpsf .
cp ../120-fit_esp/cg-list.txt .
cp ../120-fit_esp/elem-list.txt .
cp ../120-fit_esp/mol-opt.crd .
cp ../120-fit_esp/mol*.xpsf .
cp ../120-fit_esp/mol.prm .
cp ../120-fit_esp/mol.rtf .
cp ../120-fit_esp/mol-esp.dat .
cp ../120-fit_esp/elem-list.txt .
cp ../120-fit_esp/fit-mol.conf .
cp ../120-fit_esp/para-check.dat ./para-opt-start.dat

Gexe acceptor mol-opt.crd 
Gexe donor mol-opt.crd 

/usr/bin/python $GAAMPSCRIPTS/extract-qm-mol-water.py >> $LOGFILE 

if [ -e ./E-mol-wat.txt ]; then

  Gexe gen_soft_list 

  NumTorsion=`wc -l soft-dih-list.txt | awk '{print $1}'`

  echo "Target_E_Int_Water" >> fit-mol.conf
  echo "FILE_MolWater_PSF   mol-wat.xpsf" >> fit-mol.conf
  echo "FILE_MolWaterEnergy E-mol-wat.txt" >> fit-mol.conf
  echo "SCALE_QM_E_MIN          1.16" >> fit-mol.conf
  echo "SHIFT_QM_R_MIN         -0.20" >> fit-mol.conf
  echo "SHIFT_QM_R_MIN_CHARGED -0.20" >> fit-mol.conf

  if [ "$NumTorsion" -eq 0 ]; then
    Gexe fitcharge-again fit-mol.conf 
  else
    Gexe fitcharge fit-mol.conf 
  fi

  Gexe update-xpsf  

  ###added to copy some files to results folder
  mkdir -p ../results/qm
  cp final-para.txt ../results/report-esp-wat.txt
  cp mol-esp.rtf ../results/mol-esp-wat.rtf
  cp fit-mol.conf ../results/
   
  cp mm*.pdb ../results/		
 
  cp qm-mol-wat-* ../results/qm/   	 

fi

