#!/bin/sh
source $GAAMPSCRIPTS/routines

cp ../121-fit_esp_drude/* .
rm para-opt*
cp ../121-fit_esp_drude/para-check.dat ./para-opt-start.dat
cp ../150-fit_water/E-mol-wat.txt .
cp ../031-generate_drude/drude-mol-wat.xpsf .

echo "Target_E_Int_Water" >> drude-fit-mol.conf
echo "FILE_MolWater_PSF   drude-mol-wat.xpsf" >> drude-fit-mol.conf 
echo "FILE_MolWaterEnergy E-mol-wat.txt" >> drude-fit-mol.conf
echo "SCALE_QM_E_MIN_Drude          0.95" >> drude-fit-mol.conf
echo "SHIFT_QM_R_MIN_Drude         -0.15" >> drude-fit-mol.conf
echo "SHIFT_QM_R_MIN_CHARGED_Drude -0.15" >> drude-fit-mol.conf

NumTorsion=`wc -l ../150-fit_water/soft-dih-list.txt | awk '{print $1}'`

if [ "$NumTorsion" -eq 0 ]; then
  Gexe drude-fitcharge_again drude-fit-mol.conf
else
  Gexe drude-fitcharge drude-fit-mol.conf
fi

Gexe drude-gen_xpsf drude-esp-mol.rtf drude-esp-wat-mol.xpsf MOL TEST

mkdir -p ../drude-results

cp final-para.txt ../drude-results/report-esp-wat.txt
cp drude-esp-mol.rtf ../drude-results/drude-esp-wat-mol.rtf
cp drude-esp-wat-mol.xpsf ../drude-results/drude-esp-wat-mol.xpsf
cp *.pdb ../drude-results/


exit 0
