#!/bin/sh
source $GAAMPSCRIPTS/routines

cp $GAAMPRUN/120-fit_esp/elem-list.txt .

if [ "$NumTorsion" -eq 1 ]; then
  cp $GAAMPRUN/210-detect_soft_torsion/mol.prm .
  cp $GAAMPRUN/210-detect_soft_torsion/mol.xpsf .
  cp $GAAMPRUN/210-detect_soft_torsion/mol-opt.crd .
  cp $GAAMPRUN/210-detect_soft_torsion/soft-dih-list.txt .

  Gexe qm-1d-scan-single_para

  ###copying files to results folder
  cp qm-1d-phi-*.out ../results/qm/
  cp qm-scan-*.gjf ../results/qm/

  cp mol.prm ../results/mol-tor.prm
  cp mol.xpsf ../results/mol-tor.xpsf

  mkdir -p ../drude-results
  

else 
  cp $GAAMPRUN/220-pes/mol.prm .
  cp $GAAMPRUN/220-pes/mol.xpsf .
  cp $GAAMPRUN/220-pes/mol-opt.crd .
  cp $GAAMPRUN/220-pes/soft-dih-list-new.txt ./soft-dih-list.txt

  if [ "$NumTorsion" -lt "$MaxTorsion" ]; then

    Gexe qm-1d-scan-para 

  else 

    Gexe qm-1d-scan_large_para

  fi

  ###copying files to results folder
  cp qm-1d-phi-*.out ../results/qm/
  cp qm-scan-*.gjf ../results/qm/

  cp mol-*m.pdb ../results/
  cp mol-tor.rtf ../results/mol-tor.rtf
  cp mol.prm ../results/mol-tor.prm
  cp mol.xpsf ../results/mol-tor.xpsf
  cp *.png ../results/
  cp result-1D.html ../results/
  cp fitting-1d-*.dat ../results/
  cp org-1d-*.dat ../results/

  mkdir -p ../drude-results

fi

exit 0
