#!/bin/sh
source $GAAMPSCRIPTS/routines

cp ../230-qm_1d_scan/mol.prm .
cp ../230-qm_1d_scan/mol.xpsf .
cp ../230-qm_1d_scan/tor-1D-idx-*.dat .
cp ../230-qm_1d_scan/soft-dih-list.txt .

Gexe 1d-fitting

if [ "$NumTorsion" > 1 ]; then
  rm -Rf saved-para.dat
  touch saved-para.dat
  IdxTor=1
  while [  $IdxTor -le $NumTorsion ]; do
    head -n 1 torsion-para-${IdxTor}.dat >> saved-para.dat
    let IdxTor=IdxTor+1
  done
else
  head -n 1 torsion-para-1.dat > saved-para.dat
fi

### copying files to results
cp *dat ../results

$GAAMPSCRIPTS/plot-1d-result-and-org.sh
cp *png ../results

exit 0
