#!/bin/sh
source $GAAMPSCRIPTS/routines

  cp ../150-fit_water/* .
  cp ../240-1d-fitting/soft-dih-list.txt .
  cp ../240-1d-fitting/saved-para.dat .
  cp para-check.dat para-opt-start.dat

  Gexe fitcharge-again fit-mol.conf
  Gexe update-xpsf

  ####copying files to results directory
  if [ "$NumTorsion" -eq 1 ]; then
    cp mol-esp.rtf mol-tor.rtf
  fi
  cp *.rtf ../results
  cp fit-mol.conf ../results
  cp *.prm ../results
  cp new-mol.xpsf ../results/mol.xpsf

exit 0
