#!/bin/sh
source $GAAMPSCRIPTS/routines
cp ../240-1d-fitting/* .
cp ../250-refitcharges/new-mol.xpsf ./mol.xpsf
##  cp ../250-refitcharges/new-mol.xpsf ../22*-scan/mol.xpsf

Gexe 1d-fitting

rm -Rf saved-para.dat
touch saved-para.dat

IdxTor=1
while [ -e torsion-para-${IdxTor}.dat ]; do
  head -n 1 torsion-para-${IdxTor}.dat >> saved-para.dat
  let IdxTor=IdxTor+1
done

####copying files to the results directory

cp mol-*m.pdb ../results
cp mol-tor.rtf ../results
cp mol.prm ../results/mol-tor.prm
cp mol.xpsf ../results/mol-tor.xpsf

exit 0
